package kr.co.codeJ.JPA.model.factory;

import org.springframework.stereotype.Component;

import kr.co.codeJ.JPA.DAOModel.GenericDTOMapperImpl;;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Component
public class FactoryMapper extends GenericDTOMapperImpl<Factory, FactoryDTO >
 {

	FactoryMapper() {
		super(Factory.class,FactoryDTO.class);
	}

}