package com.codeJ.JPA.model.factory;

import lombok.Getter;
import lombok.Setter;
import org.springframework.stereotype.Component;

import com.codeJ.JPA.DAOModel.GenericDTO;

import org.springframework.context.annotation.Scope;

import java.util.Date;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Getter
@Setter
@Component
@Scope(value = "prototype" )
public class FactoryDTO implements GenericDTO 
 {
	private String memberCorpid;

	private String factoryid;

	private String bizNo;

	private String factorytype;

	private String fctryNm;

	private String erpcode;

	private String siteid;

	private String addr1;

	private String addr2;

	private String tph1;

	private String tph2;

	private String tph3;

	private String description;

	private String useyn;

	private String createperson;

	private Date createtime;

	private String lasteventcomment;

	private String lasteventname;

	private String lasteventperson;

	private Date lasteventtime;

	private String lasteventtimekey;

	private String cutoffCd;

	private String weekStartNm;


	public String ToString() {
		return this.toString() + super.toString();
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	@Override
	public boolean isValid() {
		return false;
	}


}