package com.codeJ.JPA.model.factory;

import lombok.Getter;
import lombok.ToString;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.IdClass;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;
import javax.persistence.Transient;

import com.codeJ.JPA.DAOModel.GenericEntity;
import com.codeJ.JPA.DAOModel.GenericEntityKeyImpl;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

//update SQL 생성 시 빈칼럼은 제거한다.
@org.hibernate.annotations.DynamicUpdate
//insert SQL 생성 시 빈칼럼은 제거한다.
@org.hibernate.annotations.DynamicInsert
@Getter
@ToString
@Entity
@Table(name="factory")
@IdClass(Factory.Key.class)
public class Factory implements GenericEntity 
 {
	@Id 
	@Column(name="member_corpid" , nullable=false , length=20)
	private String memberCorpid;

	@Id 
	@Column(name="factoryid" , nullable=false , length=20)
	private String factoryid;

	@Column(name="biz_no" , nullable=false , length=20)
	private String bizNo;

	@Column(name="factorytype" , length=15)
	private String factorytype;

	@Column(name="fctry_nm" , length=40)
	private String fctryNm;

	@Column(name="erpcode" , length=10)
	private String erpcode;

	@Column(name="siteid" , length=20)
	private String siteid;

	@Column(name="addr1" , length=100)
	private String addr1;

	@Column(name="addr2" , length=100)
	private String addr2;

	@Column(name="tph1" , length=4)
	private String tph1;

	@Column(name="tph2" , length=4)
	private String tph2;

	@Column(name="tph3" , length=4)
	private String tph3;

	@Column(name="description" , length=400)
	private String description;

	@Column(name="useyn" , length=1)
	private String useyn;

	@Column(name="createperson" , length=20)
	private String createperson;

	@Column(name="createtime" )
	@Temporal(TemporalType.TIMESTAMP)
	private Date createtime;

	@Column(name="lasteventcomment" , length=300)
	private String lasteventcomment;

	@Column(name="lasteventname" , length=50)
	private String lasteventname;

	@Column(name="lasteventperson" , length=20)
	private String lasteventperson;

	@Column(name="lasteventtime" )
	@Temporal(TemporalType.TIMESTAMP)
	private Date lasteventtime;

	@Column(name="lasteventtimekey" , length=25)
	private String lasteventtimekey;

	@Column(name="cutoff_cd" , length=20)
	private String cutoffCd;

	@Column(name="week_start_nm" , length=20)
	private String weekStartNm;


	@Transient
	private Key key;

	public String ToString() {
		return this.toString() + super.toString();
	}
	public Factory() {}
	public Factory(String memberCorpid,String factoryid) {
		if ( key == null)
			key= new Key (memberCorpid,factoryid);
	}
	public Key getKey() {
		return key;
	}
	public Key getKey(String memberCorpid,String factoryid) {
		if ( key == null)
			key= new Key (memberCorpid,factoryid);
		return key;
	}
	public static class Key extends GenericEntityKeyImpl {
		@Getter
		private String memberCorpid;
		@Getter
		private String factoryid;
		public Key() {
			super (Key.class);
		}
		public Key(String memberCorpid,String factoryid) {
			super (Key.class);
		this.memberCorpid=memberCorpid;
		this.factoryid=factoryid;
		}
	}

}