package com.codeJ.JPA.model.factory;

import org.springframework.stereotype.Repository;

import com.codeJ.JPA.DAOModel.GenericDAOImpl;

import org.springframework.beans.factory.annotation.Autowired;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Repository("FactoryDAO")
public class FactoryDAO extends GenericDAOImpl< Factory, FactoryDTO,FactoryMapper> 
 {
	@Autowired
	FactoryMapper mapper;

	public FactoryDAO() {
		super(Factory.class,FactoryDTO.class);
	}

}