package kr.co.codeJ.JPA.model.person;

import lombok.Getter;
import lombok.Setter;
import org.springframework.stereotype.Component;

import kr.co.codeJ.JPA.DAOModel.GenericDTO;

import org.springframework.context.annotation.Scope;

import java.util.Date;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Getter
@Setter
@Component
@Scope(value = "prototype" )
public class PersonDTO implements GenericDTO 
 {
	private String memberCorpid;

	private String factoryidDft;

	private String personid;

	private String personname;

	private String personclassid;

	private String password;

	private String usrFlag;

	private String userType;

	private String customerid;

	private String deptcode;

	private String email;

	private String gender;

	private String jobtitle;

	private String jobPositionCd;

	private String jobAssnCd;

	private String upperPersonId;

	private String telephone;

	private String nationCd;

	private Date joinDate;

	private Date leaveDate;

	private String useYn;

	private String sysYn;

	private Date pwChangeTime;

	private String createperson;

	private Date createtime;

	private String lasteventperson;

	private Date lasteventtime;

	private String lasteventcomment;

	private String lasteventname;

	private String lasteventtimekey;

	private String deptname;

	private String email2;

	private String tph2;

	private String tph3;


	public String ToString() {
		return this.toString() + super.toString();
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	@Override
	public boolean isValid() {
		return false;
	}


}