package com.codeJ.JPA.model.person;

import org.springframework.stereotype.Repository;

import com.codeJ.JPA.DAOModel.GenericDAOImpl;

import org.springframework.beans.factory.annotation.Autowired;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Repository("PersonDAO")
public class PersonDAO extends GenericDAOImpl< Person, PersonDTO,PersonMapper> 
 {
	@Autowired
	PersonMapper mapper;

	public PersonDAO() {
		super(Person.class,PersonDTO.class);
	}

}