package com.udmtek.DBCore.model.person;

import org.springframework.stereotype.Component;
import com.udmtek.DBCore.DAOModel.DBCoreDTOMapperImpl;;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Component
public class PersonMapper extends DBCoreDTOMapperImpl<Person, PersonDTO >
 {

	PersonMapper() {
		super(Person.class,PersonDTO.class);
	}

}