package kr.co.codeJ.JPA.model.person;

import org.springframework.stereotype.Component;

import kr.co.codeJ.JPA.DAOModel.GenericDTOMapperImpl;;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.2.0
* generated by DBCoreGen
*/

@Component
public class PersonMapper extends GenericDTOMapperImpl<Person, PersonDTO >
 {

	PersonMapper() {
		super(Person.class,PersonDTO.class);
	}

}