package com.udmtek.DBCore.model.factory;
import org.springframework.stereotype.Component;
import com.udmtek.DBCore.DAOModel.DBCoreDTOMapperImpl;
/***
* @author julu1 <julu1 @ naver.com >
* @version 0.1.0
* generated by DBCoreGen
*/

@Component
public class FactoryMapper extends DBCoreDTOMapperImpl< Factory, FactoryDTO > {

	FactoryMapper() {
		super(Factory.class,FactoryDTO.class);
	}
}
