package com.udmtek.DBCore.model.factory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import com.udmtek.DBCore.DAOModel.GenericDAOImpl;

/***
* @author julu1 <julu1 @ naver.com >
* @version 0.1.0
* generated by DBCoreGen
*/

@Repository("FactoryDAO")
public class FactoryDAO extends GenericDAOImpl< Factory, FactoryDTO, FactoryMapper >  {
	@Autowired
	FactoryMapper mapper;

	public FactoryDAO() {
		super(Factory.class,FactoryDTO.class);
	}
}
