package com.udmtek.DBCore.model.factory;
import java.util.Date;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.udmtek.DBCore.DAOModel.DBCoreDTO;
import com.udmtek.DBCore.DAOModel.DBCoreDTOImpl;
import lombok.Getter;
import lombok.Setter;
/***
* @author julu1 <julu1 @ naver.com >
* @version 0.1.0
* generated by DBCoreGen
*/

@Getter
@Setter
@Component
@Scope(value = "prototype" )

public class FactoryDTO extends DBCoreDTOImpl {
	private String memberCorpid;
	private String factoryid;
	private String bizNo;
	private String factorytype;
	private String fctryNm;
	private String erpcode;
	private String siteid;
	private String addr1;
	private String addr2;
	private String tph1;
	private String tph2;
	private String tph3;
	private String description;
	private String useyn;
	private String cutoffCd;
	private String weekStartNm;
	public String ToString() {
		return this.toString() + super.toString();
	}
	public String toString() {
		return this.ToString();
	}
	@Override
	public Object clone() throws CloneNotSupportedException{
		return super.clone();
	}

}
